spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/habitTrackerDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

ase:
  url: "http://localhost:8080"

logging:
  level:
    org.springframework.security: DEBUG
